import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { validateRequest } from "@/auth";
import { redirect } from "next/navigation";
import SessionProvider from "../utils/sessionProvider";
import ReactQueryProvider from "../reactQueryProvider";
import LeftSide from "./leftSide";
import { useEffect } from "react";
import { PusherProvider } from "../utils/pusherProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await validateRequest();

  if (!session.user) redirect("/login");

  return (
    <PusherProvider>
      <ReactQueryProvider>
        <SessionProvider value={session}>
          <main className="flex max-h-screen flex-row bg-card-foreground p-4  text-[12px] font-normal text-slate-400 ">
            <LeftSide />
            {children}
          </main>
        </SessionProvider>
      </ReactQueryProvider>
    </PusherProvider>
  );
}
